use_lockfile = false

[project]
name = "hyperion.tables"
r_version = "4.5"

repositories = [
  { alias = "prism", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2026-03-18" },
  { alias = "hyp-eco", url = "https://prism.dev.a2-ai.cloud/rpkgs/hyperion-eco/v1/" },
]

dependencies = [
  # dev dependencies
  "devtools",
  { name = "covr", install_suggestions = true },
  #{ name = "pkgload", path = "../pkgload" },
  { name = "roxygen2", git = "https://github.com/r-lib/roxygen2", branch = "main" },
  { name = "doclisting", git = "https://github.com/r-lib/doclisting", branch = "main" },
  #{ name = "starlightr", git = "https://github.com/a2-ai/starlightr", branch = "main" },

  "hyperion",
  { name = "hyperion.tables", path = ".", dependencies_only = false, install_suggestions = true },
  "lobstr",
]
